// Code generated by {{ .AppName }}. DO NOT EDIT.

package {{ .Version }}

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// Generated from Certificate.cert-manager.io/v1 CRD

// +kubebuilder:object:root=true

// {{ .List }} is a list of {{ .Plural }}.
type {{ .List }} struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Items []{{ .Kind }} `json:"items"`
}

// +kubebuilder:object:root=true

{{ if .Root.Description }}// {{ .Root.Description  }}{{ end }}
type {{ .Kind }} struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	{{- range .Root.Fields }}
	{{ if .Description }}// {{ .Description }}{{ end}}
	{{ .Name }} {{ .Type }} `json:{{ .JSONTag }},omitempty`
	{{- end }}
}

dadsfasdfsadf
{{ range .Structs }}
{{ if .Description }}// {{ .Description  }}{{ end }}
type {{ .Name }} struct {
	{{- range .Fields }}
	{{ if .Description }}// {{ .Description }}{{ end}}
	{{ .Name }} {{ .Type }} `json:{{ .JSONTag }},omitempty`
	{{- end }}
}
{{ end }}
