//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certificate) DeepCopyInto(out *Certificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certificate.
func (in *Certificate) DeepCopy() *Certificate {
	if in == nil {
		return nil
	}
	out := new(Certificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Certificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpec) DeepCopyInto(out *CertificateSpec) {
	*out = *in
	if in.Othernames != nil {
		in, out := &in.Othernames, &out.Othernames
		*out = make([]any, len(*in))
		for i := range *in {
		}
	}
	out.Privatekey = in.Privatekey
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Additionaloutputformats != nil {
		in, out := &in.Additionaloutputformats, &out.Additionaloutputformats
		*out = make([]any, len(*in))
		for i := range *in {
		}
	}
	if in.Dnsnames != nil {
		in, out := &in.Dnsnames, &out.Dnsnames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Emailaddresses != nil {
		in, out := &in.Emailaddresses, &out.Emailaddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ipaddresses != nil {
		in, out := &in.Ipaddresses, &out.Ipaddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Nameconstraints.DeepCopyInto(&out.Nameconstraints)
	in.Subject.DeepCopyInto(&out.Subject)
	if in.Uris != nil {
		in, out := &in.Uris, &out.Uris
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Issuerref = in.Issuerref
	out.Keystores = in.Keystores
	in.Secrettemplate.DeepCopyInto(&out.Secrettemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpec.
func (in *CertificateSpec) DeepCopy() *CertificateSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecIssuerref) DeepCopyInto(out *CertificateSpecIssuerref) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecIssuerref.
func (in *CertificateSpecIssuerref) DeepCopy() *CertificateSpecIssuerref {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecIssuerref)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecKeystores) DeepCopyInto(out *CertificateSpecKeystores) {
	*out = *in
	out.Jks = in.Jks
	out.Pkcs12 = in.Pkcs12
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecKeystores.
func (in *CertificateSpecKeystores) DeepCopy() *CertificateSpecKeystores {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecKeystores)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecKeystoresJks) DeepCopyInto(out *CertificateSpecKeystoresJks) {
	*out = *in
	out.Passwordsecretref = in.Passwordsecretref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecKeystoresJks.
func (in *CertificateSpecKeystoresJks) DeepCopy() *CertificateSpecKeystoresJks {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecKeystoresJks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecKeystoresJksPasswordsecretref) DeepCopyInto(out *CertificateSpecKeystoresJksPasswordsecretref) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecKeystoresJksPasswordsecretref.
func (in *CertificateSpecKeystoresJksPasswordsecretref) DeepCopy() *CertificateSpecKeystoresJksPasswordsecretref {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecKeystoresJksPasswordsecretref)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecKeystoresPkcs12) DeepCopyInto(out *CertificateSpecKeystoresPkcs12) {
	*out = *in
	out.Passwordsecretref = in.Passwordsecretref
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecKeystoresPkcs12.
func (in *CertificateSpecKeystoresPkcs12) DeepCopy() *CertificateSpecKeystoresPkcs12 {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecKeystoresPkcs12)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecKeystoresPkcs12Passwordsecretref) DeepCopyInto(out *CertificateSpecKeystoresPkcs12Passwordsecretref) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecKeystoresPkcs12Passwordsecretref.
func (in *CertificateSpecKeystoresPkcs12Passwordsecretref) DeepCopy() *CertificateSpecKeystoresPkcs12Passwordsecretref {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecKeystoresPkcs12Passwordsecretref)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecNameconstraints) DeepCopyInto(out *CertificateSpecNameconstraints) {
	*out = *in
	in.Permitted.DeepCopyInto(&out.Permitted)
	in.Excluded.DeepCopyInto(&out.Excluded)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecNameconstraints.
func (in *CertificateSpecNameconstraints) DeepCopy() *CertificateSpecNameconstraints {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecNameconstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecNameconstraintsExcluded) DeepCopyInto(out *CertificateSpecNameconstraintsExcluded) {
	*out = *in
	if in.Dnsdomains != nil {
		in, out := &in.Dnsdomains, &out.Dnsdomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Emailaddresses != nil {
		in, out := &in.Emailaddresses, &out.Emailaddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ipranges != nil {
		in, out := &in.Ipranges, &out.Ipranges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Uridomains != nil {
		in, out := &in.Uridomains, &out.Uridomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecNameconstraintsExcluded.
func (in *CertificateSpecNameconstraintsExcluded) DeepCopy() *CertificateSpecNameconstraintsExcluded {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecNameconstraintsExcluded)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecNameconstraintsPermitted) DeepCopyInto(out *CertificateSpecNameconstraintsPermitted) {
	*out = *in
	if in.Ipranges != nil {
		in, out := &in.Ipranges, &out.Ipranges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Uridomains != nil {
		in, out := &in.Uridomains, &out.Uridomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Dnsdomains != nil {
		in, out := &in.Dnsdomains, &out.Dnsdomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Emailaddresses != nil {
		in, out := &in.Emailaddresses, &out.Emailaddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecNameconstraintsPermitted.
func (in *CertificateSpecNameconstraintsPermitted) DeepCopy() *CertificateSpecNameconstraintsPermitted {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecNameconstraintsPermitted)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecPrivatekey) DeepCopyInto(out *CertificateSpecPrivatekey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecPrivatekey.
func (in *CertificateSpecPrivatekey) DeepCopy() *CertificateSpecPrivatekey {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecPrivatekey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecSecrettemplate) DeepCopyInto(out *CertificateSpecSecrettemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecSecrettemplate.
func (in *CertificateSpecSecrettemplate) DeepCopy() *CertificateSpecSecrettemplate {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecSecrettemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpecSubject) DeepCopyInto(out *CertificateSpecSubject) {
	*out = *in
	if in.Localities != nil {
		in, out := &in.Localities, &out.Localities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Organizationalunits != nil {
		in, out := &in.Organizationalunits, &out.Organizationalunits
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Organizations != nil {
		in, out := &in.Organizations, &out.Organizations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Postalcodes != nil {
		in, out := &in.Postalcodes, &out.Postalcodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Provinces != nil {
		in, out := &in.Provinces, &out.Provinces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Streetaddresses != nil {
		in, out := &in.Streetaddresses, &out.Streetaddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Countries != nil {
		in, out := &in.Countries, &out.Countries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpecSubject.
func (in *CertificateSpecSubject) DeepCopy() *CertificateSpecSubject {
	if in == nil {
		return nil
	}
	out := new(CertificateSpecSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateStatus) DeepCopyInto(out *CertificateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]any, len(*in))
		for i := range *in {
		}
	}
	in.Lastfailuretime.DeepCopyInto(&out.Lastfailuretime)
	in.Notafter.DeepCopyInto(&out.Notafter)
	in.Notbefore.DeepCopyInto(&out.Notbefore)
	in.Renewaltime.DeepCopyInto(&out.Renewaltime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateStatus.
func (in *CertificateStatus) DeepCopy() *CertificateStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateStatus)
	in.DeepCopyInto(out)
	return out
}
