//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by crd-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:generate=true

// +kubebuilder:object:root=true

// AllCaseList is a list of Allcases.
type AllCaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []AllCase `json:"items"`
}

// +kubebuilder:object:root=true

// AllCase represents a AllCase
type AllCase struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec AllCaseSpec `json:"spec,omitempty"`
}


// AllCaseSpec represents a AllCase.spec
type AllCaseSpec struct {
	ArrayOfObjects []ArrayOfObjects `json:"arrayOfObjects,omitempty"`
	ArrayOfString []string `json:"arrayOfString,omitempty"`
	BinaryField []byte `json:"binaryField,omitempty"`
	BoolField bool `json:"boolField,omitempty"`
	ByteField []byte `json:"byteField,omitempty"`
	DateTimeField metav1.Time `json:"dateTimeField,omitempty"`
	DefaultFloatField float64 `json:"defaultFloatField,omitempty"`
	DefaultIntField int64 `json:"defaultIntField,omitempty"`
	EmptyObjectField runtime.RawExtension `json:"emptyObjectField,omitempty"`
	EnumField EnumField `json:"enumField,omitempty"`
	Float32Field float32 `json:"float32Field,omitempty"`
	Float64Field float64 `json:"float64Field,omitempty"`
	Int32Field int32 `json:"int32Field,omitempty"`
	Int64Field int64 `json:"int64Field,omitempty"`
	IntOrStringField intstr.IntOrString `json:"intOrStringField,omitempty"`
	MapField map[string]string `json:"mapField,omitempty"`
	ObjectField ObjectField `json:"objectField,omitempty"`
	RawExtensionField runtime.RawExtension `json:"rawExtensionField,omitempty"`
	StringField string `json:"stringField,omitempty"`
}

// ArrayOfObjects represents a AllCase.spec.arrayOfObjects
type ArrayOfObjects struct {
	NestedArrayString string `json:"nestedArrayString,omitempty"`
}

// ObjectField represents a AllCase.spec.objectField
type ObjectField struct {
	NestedInt int64 `json:"nestedInt,omitempty"`
	NestedString string `json:"nestedString,omitempty"`
}

// EnumField represents an enumeration for EnumField
type EnumField string

var (
	// EnumFieldValue1 EnumField enum value "Value1"
	EnumFieldValue1 EnumField = "Value1"
	// EnumFieldValue2 EnumField enum value "Value2"
	EnumFieldValue2 EnumField = "Value2"
	// EnumFieldEmptyValue EnumField enum value ""
	EnumFieldEmptyValue EnumField = ""
	// EnumFieldAll EnumField enum value "*"
	EnumFieldAll EnumField = "*"
)

