//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certificate) DeepCopyInto(out *Certificate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certificate.
func (in *Certificate) DeepCopy() *Certificate {
	if in == nil {
		return nil
	}
	out := new(Certificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Certificate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateAdditionalOutputFormats) DeepCopyInto(out *CertificateAdditionalOutputFormats) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateAdditionalOutputFormats.
func (in *CertificateAdditionalOutputFormats) DeepCopy() *CertificateAdditionalOutputFormats {
	if in == nil {
		return nil
	}
	out := new(CertificateAdditionalOutputFormats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateConditions) DeepCopyInto(out *CertificateConditions) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateConditions.
func (in *CertificateConditions) DeepCopy() *CertificateConditions {
	if in == nil {
		return nil
	}
	out := new(CertificateConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateExcluded) DeepCopyInto(out *CertificateExcluded) {
	*out = *in
	if in.DnsDomains != nil {
		in, out := &in.DnsDomains, &out.DnsDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EmailAddresses != nil {
		in, out := &in.EmailAddresses, &out.EmailAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IpRanges != nil {
		in, out := &in.IpRanges, &out.IpRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UriDomains != nil {
		in, out := &in.UriDomains, &out.UriDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateExcluded.
func (in *CertificateExcluded) DeepCopy() *CertificateExcluded {
	if in == nil {
		return nil
	}
	out := new(CertificateExcluded)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateIssuerRef) DeepCopyInto(out *CertificateIssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateIssuerRef.
func (in *CertificateIssuerRef) DeepCopy() *CertificateIssuerRef {
	if in == nil {
		return nil
	}
	out := new(CertificateIssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateJks) DeepCopyInto(out *CertificateJks) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateJks.
func (in *CertificateJks) DeepCopy() *CertificateJks {
	if in == nil {
		return nil
	}
	out := new(CertificateJks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateKeystores) DeepCopyInto(out *CertificateKeystores) {
	*out = *in
	out.Jks = in.Jks
	out.Pkcs12 = in.Pkcs12
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateKeystores.
func (in *CertificateKeystores) DeepCopy() *CertificateKeystores {
	if in == nil {
		return nil
	}
	out := new(CertificateKeystores)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateList) DeepCopyInto(out *CertificateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Certificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateList.
func (in *CertificateList) DeepCopy() *CertificateList {
	if in == nil {
		return nil
	}
	out := new(CertificateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateNameConstraints) DeepCopyInto(out *CertificateNameConstraints) {
	*out = *in
	in.Excluded.DeepCopyInto(&out.Excluded)
	in.Permitted.DeepCopyInto(&out.Permitted)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateNameConstraints.
func (in *CertificateNameConstraints) DeepCopy() *CertificateNameConstraints {
	if in == nil {
		return nil
	}
	out := new(CertificateNameConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateOtherNames) DeepCopyInto(out *CertificateOtherNames) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateOtherNames.
func (in *CertificateOtherNames) DeepCopy() *CertificateOtherNames {
	if in == nil {
		return nil
	}
	out := new(CertificateOtherNames)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificatePasswordSecretRef) DeepCopyInto(out *CertificatePasswordSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificatePasswordSecretRef.
func (in *CertificatePasswordSecretRef) DeepCopy() *CertificatePasswordSecretRef {
	if in == nil {
		return nil
	}
	out := new(CertificatePasswordSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificatePkcs12) DeepCopyInto(out *CertificatePkcs12) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificatePkcs12.
func (in *CertificatePkcs12) DeepCopy() *CertificatePkcs12 {
	if in == nil {
		return nil
	}
	out := new(CertificatePkcs12)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificatePrivateKey) DeepCopyInto(out *CertificatePrivateKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificatePrivateKey.
func (in *CertificatePrivateKey) DeepCopy() *CertificatePrivateKey {
	if in == nil {
		return nil
	}
	out := new(CertificatePrivateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequest) DeepCopyInto(out *CertificateRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequest.
func (in *CertificateRequest) DeepCopy() *CertificateRequest {
	if in == nil {
		return nil
	}
	out := new(CertificateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestConditions) DeepCopyInto(out *CertificateRequestConditions) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestConditions.
func (in *CertificateRequestConditions) DeepCopy() *CertificateRequestConditions {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestIssuerRef) DeepCopyInto(out *CertificateRequestIssuerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestIssuerRef.
func (in *CertificateRequestIssuerRef) DeepCopy() *CertificateRequestIssuerRef {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestIssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestList) DeepCopyInto(out *CertificateRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertificateRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestList.
func (in *CertificateRequestList) DeepCopy() *CertificateRequestList {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertificateRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestSpec) DeepCopyInto(out *CertificateRequestSpec) {
	*out = *in
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.IssuerRef = in.IssuerRef
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]CertificateRequestUsages, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestSpec.
func (in *CertificateRequestSpec) DeepCopy() *CertificateRequestSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateRequestStatus) DeepCopyInto(out *CertificateRequestStatus) {
	*out = *in
	if in.Ca != nil {
		in, out := &in.Ca, &out.Ca
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CertificateRequestConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.FailureTime.DeepCopyInto(&out.FailureTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateRequestStatus.
func (in *CertificateRequestStatus) DeepCopy() *CertificateRequestStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSecretTemplate) DeepCopyInto(out *CertificateSecretTemplate) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSecretTemplate.
func (in *CertificateSecretTemplate) DeepCopy() *CertificateSecretTemplate {
	if in == nil {
		return nil
	}
	out := new(CertificateSecretTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSpec) DeepCopyInto(out *CertificateSpec) {
	*out = *in
	if in.AdditionalOutputFormats != nil {
		in, out := &in.AdditionalOutputFormats, &out.AdditionalOutputFormats
		*out = make([]CertificateAdditionalOutputFormats, len(*in))
		copy(*out, *in)
	}
	if in.DnsNames != nil {
		in, out := &in.DnsNames, &out.DnsNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EmailAddresses != nil {
		in, out := &in.EmailAddresses, &out.EmailAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IpAddresses != nil {
		in, out := &in.IpAddresses, &out.IpAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.IssuerRef = in.IssuerRef
	out.Keystores = in.Keystores
	in.NameConstraints.DeepCopyInto(&out.NameConstraints)
	if in.OtherNames != nil {
		in, out := &in.OtherNames, &out.OtherNames
		*out = make([]CertificateOtherNames, len(*in))
		copy(*out, *in)
	}
	out.PrivateKey = in.PrivateKey
	in.SecretTemplate.DeepCopyInto(&out.SecretTemplate)
	in.Subject.DeepCopyInto(&out.Subject)
	if in.Uris != nil {
		in, out := &in.Uris, &out.Uris
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]CertificateUsages, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSpec.
func (in *CertificateSpec) DeepCopy() *CertificateSpec {
	if in == nil {
		return nil
	}
	out := new(CertificateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateStatus) DeepCopyInto(out *CertificateStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]CertificateConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastFailureTime.DeepCopyInto(&out.LastFailureTime)
	in.NotAfter.DeepCopyInto(&out.NotAfter)
	in.NotBefore.DeepCopyInto(&out.NotBefore)
	in.RenewalTime.DeepCopyInto(&out.RenewalTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateStatus.
func (in *CertificateStatus) DeepCopy() *CertificateStatus {
	if in == nil {
		return nil
	}
	out := new(CertificateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateSubject) DeepCopyInto(out *CertificateSubject) {
	*out = *in
	if in.Countries != nil {
		in, out := &in.Countries, &out.Countries
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Localities != nil {
		in, out := &in.Localities, &out.Localities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OrganizationalUnits != nil {
		in, out := &in.OrganizationalUnits, &out.OrganizationalUnits
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Organizations != nil {
		in, out := &in.Organizations, &out.Organizations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostalCodes != nil {
		in, out := &in.PostalCodes, &out.PostalCodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Provinces != nil {
		in, out := &in.Provinces, &out.Provinces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StreetAddresses != nil {
		in, out := &in.StreetAddresses, &out.StreetAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateSubject.
func (in *CertificateSubject) DeepCopy() *CertificateSubject {
	if in == nil {
		return nil
	}
	out := new(CertificateSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuer) DeepCopyInto(out *ClusterIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuer.
func (in *ClusterIssuer) DeepCopy() *ClusterIssuer {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerAcme) DeepCopyInto(out *ClusterIssuerAcme) {
	*out = *in
	if in.CaBundle != nil {
		in, out := &in.CaBundle, &out.CaBundle
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	out.ExternalAccountBinding = in.ExternalAccountBinding
	out.PrivateKeySecretRef = in.PrivateKeySecretRef
	if in.Solvers != nil {
		in, out := &in.Solvers, &out.Solvers
		*out = make([]ClusterIssuerSolvers, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerAcme.
func (in *ClusterIssuerAcme) DeepCopy() *ClusterIssuerAcme {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerAcme)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerAcme1) DeepCopyInto(out *ClusterIssuerAcme1) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerAcme1.
func (in *ClusterIssuerAcme1) DeepCopy() *ClusterIssuerAcme1 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerAcme1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerAcmeDNS) DeepCopyInto(out *ClusterIssuerAcmeDNS) {
	*out = *in
	out.AccountSecretRef = in.AccountSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerAcmeDNS.
func (in *ClusterIssuerAcmeDNS) DeepCopy() *ClusterIssuerAcmeDNS {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerAcmeDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerAffinity) DeepCopyInto(out *ClusterIssuerAffinity) {
	*out = *in
	in.NodeAffinity.DeepCopyInto(&out.NodeAffinity)
	in.PodAffinity.DeepCopyInto(&out.PodAffinity)
	in.PodAntiAffinity.DeepCopyInto(&out.PodAntiAffinity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerAffinity.
func (in *ClusterIssuerAffinity) DeepCopy() *ClusterIssuerAffinity {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerAkamai) DeepCopyInto(out *ClusterIssuerAkamai) {
	*out = *in
	out.AccessTokenSecretRef = in.AccessTokenSecretRef
	out.ClientSecretSecretRef = in.ClientSecretSecretRef
	out.ClientTokenSecretRef = in.ClientTokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerAkamai.
func (in *ClusterIssuerAkamai) DeepCopy() *ClusterIssuerAkamai {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerAkamai)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerAppRole) DeepCopyInto(out *ClusterIssuerAppRole) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerAppRole.
func (in *ClusterIssuerAppRole) DeepCopy() *ClusterIssuerAppRole {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerAppRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerAuth) DeepCopyInto(out *ClusterIssuerAuth) {
	*out = *in
	in.Kubernetes.DeepCopyInto(&out.Kubernetes)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerAuth.
func (in *ClusterIssuerAuth) DeepCopy() *ClusterIssuerAuth {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerAuth1) DeepCopyInto(out *ClusterIssuerAuth1) {
	*out = *in
	out.AppRole = in.AppRole
	out.ClientCertificate = in.ClientCertificate
	in.Kubernetes.DeepCopyInto(&out.Kubernetes)
	out.TokenSecretRef = in.TokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerAuth1.
func (in *ClusterIssuerAuth1) DeepCopy() *ClusterIssuerAuth1 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerAuth1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerAzureDNS) DeepCopyInto(out *ClusterIssuerAzureDNS) {
	*out = *in
	out.ClientSecretSecretRef = in.ClientSecretSecretRef
	out.ManagedIdentity = in.ManagedIdentity
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerAzureDNS.
func (in *ClusterIssuerAzureDNS) DeepCopy() *ClusterIssuerAzureDNS {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerAzureDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerCa) DeepCopyInto(out *ClusterIssuerCa) {
	*out = *in
	if in.CrlDistributionPoints != nil {
		in, out := &in.CrlDistributionPoints, &out.CrlDistributionPoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IssuingCertificateURLs != nil {
		in, out := &in.IssuingCertificateURLs, &out.IssuingCertificateURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OcspServers != nil {
		in, out := &in.OcspServers, &out.OcspServers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerCa.
func (in *ClusterIssuerCa) DeepCopy() *ClusterIssuerCa {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerCa)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerClientCertificate) DeepCopyInto(out *ClusterIssuerClientCertificate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerClientCertificate.
func (in *ClusterIssuerClientCertificate) DeepCopy() *ClusterIssuerClientCertificate {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerClientCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerCloud) DeepCopyInto(out *ClusterIssuerCloud) {
	*out = *in
	out.ApiTokenSecretRef = in.ApiTokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerCloud.
func (in *ClusterIssuerCloud) DeepCopy() *ClusterIssuerCloud {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerCloud)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerCloudDNS) DeepCopyInto(out *ClusterIssuerCloudDNS) {
	*out = *in
	out.ServiceAccountSecretRef = in.ServiceAccountSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerCloudDNS.
func (in *ClusterIssuerCloudDNS) DeepCopy() *ClusterIssuerCloudDNS {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerCloudDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerCloudflare) DeepCopyInto(out *ClusterIssuerCloudflare) {
	*out = *in
	out.ApiKeySecretRef = in.ApiKeySecretRef
	out.ApiTokenSecretRef = in.ApiTokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerCloudflare.
func (in *ClusterIssuerCloudflare) DeepCopy() *ClusterIssuerCloudflare {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerCloudflare)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerConditions) DeepCopyInto(out *ClusterIssuerConditions) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerConditions.
func (in *ClusterIssuerConditions) DeepCopy() *ClusterIssuerConditions {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerCredentialsRef) DeepCopyInto(out *ClusterIssuerCredentialsRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerCredentialsRef.
func (in *ClusterIssuerCredentialsRef) DeepCopy() *ClusterIssuerCredentialsRef {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerCredentialsRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerDigitalocean) DeepCopyInto(out *ClusterIssuerDigitalocean) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerDigitalocean.
func (in *ClusterIssuerDigitalocean) DeepCopy() *ClusterIssuerDigitalocean {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerDigitalocean)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerDns01) DeepCopyInto(out *ClusterIssuerDns01) {
	*out = *in
	out.AcmeDNS = in.AcmeDNS
	out.Akamai = in.Akamai
	out.AzureDNS = in.AzureDNS
	out.CloudDNS = in.CloudDNS
	out.Cloudflare = in.Cloudflare
	out.Digitalocean = in.Digitalocean
	out.Rfc2136 = in.Rfc2136
	in.Route53.DeepCopyInto(&out.Route53)
	in.Webhook.DeepCopyInto(&out.Webhook)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerDns01.
func (in *ClusterIssuerDns01) DeepCopy() *ClusterIssuerDns01 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerDns01)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerExternalAccountBinding) DeepCopyInto(out *ClusterIssuerExternalAccountBinding) {
	*out = *in
	out.KeySecretRef = in.KeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerExternalAccountBinding.
func (in *ClusterIssuerExternalAccountBinding) DeepCopy() *ClusterIssuerExternalAccountBinding {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerExternalAccountBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerGatewayHTTPRoute) DeepCopyInto(out *ClusterIssuerGatewayHTTPRoute) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ParentRefs != nil {
		in, out := &in.ParentRefs, &out.ParentRefs
		*out = make([]ClusterIssuerParentRefs, len(*in))
		copy(*out, *in)
	}
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerGatewayHTTPRoute.
func (in *ClusterIssuerGatewayHTTPRoute) DeepCopy() *ClusterIssuerGatewayHTTPRoute {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerGatewayHTTPRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerHttp01) DeepCopyInto(out *ClusterIssuerHttp01) {
	*out = *in
	in.GatewayHTTPRoute.DeepCopyInto(&out.GatewayHTTPRoute)
	in.Ingress.DeepCopyInto(&out.Ingress)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerHttp01.
func (in *ClusterIssuerHttp01) DeepCopy() *ClusterIssuerHttp01 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerHttp01)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerImagePullSecrets) DeepCopyInto(out *ClusterIssuerImagePullSecrets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerImagePullSecrets.
func (in *ClusterIssuerImagePullSecrets) DeepCopy() *ClusterIssuerImagePullSecrets {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerImagePullSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerIngress) DeepCopyInto(out *ClusterIssuerIngress) {
	*out = *in
	in.IngressTemplate.DeepCopyInto(&out.IngressTemplate)
	in.PodTemplate.DeepCopyInto(&out.PodTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerIngress.
func (in *ClusterIssuerIngress) DeepCopy() *ClusterIssuerIngress {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerIngressTemplate) DeepCopyInto(out *ClusterIssuerIngressTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerIngressTemplate.
func (in *ClusterIssuerIngressTemplate) DeepCopy() *ClusterIssuerIngressTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerIngressTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerKeySecretRef) DeepCopyInto(out *ClusterIssuerKeySecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerKeySecretRef.
func (in *ClusterIssuerKeySecretRef) DeepCopy() *ClusterIssuerKeySecretRef {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerKeySecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerKubernetes) DeepCopyInto(out *ClusterIssuerKubernetes) {
	*out = *in
	in.ServiceAccountRef.DeepCopyInto(&out.ServiceAccountRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerKubernetes.
func (in *ClusterIssuerKubernetes) DeepCopy() *ClusterIssuerKubernetes {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerKubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerKubernetes1) DeepCopyInto(out *ClusterIssuerKubernetes1) {
	*out = *in
	out.SecretRef = in.SecretRef
	in.ServiceAccountRef.DeepCopyInto(&out.ServiceAccountRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerKubernetes1.
func (in *ClusterIssuerKubernetes1) DeepCopy() *ClusterIssuerKubernetes1 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerKubernetes1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerLabelSelector) DeepCopyInto(out *ClusterIssuerLabelSelector) {
	*out = *in
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]ClusterIssuerMatchExpressions1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerLabelSelector.
func (in *ClusterIssuerLabelSelector) DeepCopy() *ClusterIssuerLabelSelector {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerLabelSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerList) DeepCopyInto(out *ClusterIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerList.
func (in *ClusterIssuerList) DeepCopy() *ClusterIssuerList {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerManagedIdentity) DeepCopyInto(out *ClusterIssuerManagedIdentity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerManagedIdentity.
func (in *ClusterIssuerManagedIdentity) DeepCopy() *ClusterIssuerManagedIdentity {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerManagedIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerMatchExpressions) DeepCopyInto(out *ClusterIssuerMatchExpressions) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerMatchExpressions.
func (in *ClusterIssuerMatchExpressions) DeepCopy() *ClusterIssuerMatchExpressions {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerMatchExpressions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerMatchExpressions1) DeepCopyInto(out *ClusterIssuerMatchExpressions1) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerMatchExpressions1.
func (in *ClusterIssuerMatchExpressions1) DeepCopy() *ClusterIssuerMatchExpressions1 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerMatchExpressions1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerMetadata) DeepCopyInto(out *ClusterIssuerMetadata) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerMetadata.
func (in *ClusterIssuerMetadata) DeepCopy() *ClusterIssuerMetadata {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerMetadata1) DeepCopyInto(out *ClusterIssuerMetadata1) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerMetadata1.
func (in *ClusterIssuerMetadata1) DeepCopy() *ClusterIssuerMetadata1 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerMetadata1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerNodeAffinity) DeepCopyInto(out *ClusterIssuerNodeAffinity) {
	*out = *in
	if in.PreferredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.PreferredDuringSchedulingIgnoredDuringExecution, &out.PreferredDuringSchedulingIgnoredDuringExecution
		*out = make([]ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.RequiredDuringSchedulingIgnoredDuringExecution.DeepCopyInto(&out.RequiredDuringSchedulingIgnoredDuringExecution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerNodeAffinity.
func (in *ClusterIssuerNodeAffinity) DeepCopy() *ClusterIssuerNodeAffinity {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerNodeAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerNodeSelectorTerms) DeepCopyInto(out *ClusterIssuerNodeSelectorTerms) {
	*out = *in
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]ClusterIssuerMatchExpressions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchFields != nil {
		in, out := &in.MatchFields, &out.MatchFields
		*out = make([]ClusterIssuerMatchExpressions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerNodeSelectorTerms.
func (in *ClusterIssuerNodeSelectorTerms) DeepCopy() *ClusterIssuerNodeSelectorTerms {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerNodeSelectorTerms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerParentRefs) DeepCopyInto(out *ClusterIssuerParentRefs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerParentRefs.
func (in *ClusterIssuerParentRefs) DeepCopy() *ClusterIssuerParentRefs {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerParentRefs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerPodAffinity) DeepCopyInto(out *ClusterIssuerPodAffinity) {
	*out = *in
	if in.PreferredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.PreferredDuringSchedulingIgnoredDuringExecution, &out.PreferredDuringSchedulingIgnoredDuringExecution
		*out = make([]ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequiredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.RequiredDuringSchedulingIgnoredDuringExecution, &out.RequiredDuringSchedulingIgnoredDuringExecution
		*out = make([]ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerPodAffinity.
func (in *ClusterIssuerPodAffinity) DeepCopy() *ClusterIssuerPodAffinity {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerPodAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerPodAntiAffinity) DeepCopyInto(out *ClusterIssuerPodAntiAffinity) {
	*out = *in
	if in.PreferredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.PreferredDuringSchedulingIgnoredDuringExecution, &out.PreferredDuringSchedulingIgnoredDuringExecution
		*out = make([]ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RequiredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.RequiredDuringSchedulingIgnoredDuringExecution, &out.RequiredDuringSchedulingIgnoredDuringExecution
		*out = make([]ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution1, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerPodAntiAffinity.
func (in *ClusterIssuerPodAntiAffinity) DeepCopy() *ClusterIssuerPodAntiAffinity {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerPodAntiAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerPodTemplate) DeepCopyInto(out *ClusterIssuerPodTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerPodTemplate.
func (in *ClusterIssuerPodTemplate) DeepCopy() *ClusterIssuerPodTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerPodTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution) DeepCopyInto(out *ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution) {
	*out = *in
	in.Preference.DeepCopyInto(&out.Preference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution.
func (in *ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution) DeepCopy() *ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution1) DeepCopyInto(out *ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution1) {
	*out = *in
	in.PodAffinityTerm.DeepCopyInto(&out.PodAffinityTerm)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution1.
func (in *ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution1) DeepCopy() *ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution1 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerPreferredDuringSchedulingIgnoredDuringExecution1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution) DeepCopyInto(out *ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution) {
	*out = *in
	if in.NodeSelectorTerms != nil {
		in, out := &in.NodeSelectorTerms, &out.NodeSelectorTerms
		*out = make([]ClusterIssuerNodeSelectorTerms, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution.
func (in *ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution) DeepCopy() *ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution1) DeepCopyInto(out *ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution1) {
	*out = *in
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
	if in.MatchLabelKeys != nil {
		in, out := &in.MatchLabelKeys, &out.MatchLabelKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MismatchLabelKeys != nil {
		in, out := &in.MismatchLabelKeys, &out.MismatchLabelKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution1.
func (in *ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution1) DeepCopy() *ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution1 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerRequiredDuringSchedulingIgnoredDuringExecution1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerRfc2136) DeepCopyInto(out *ClusterIssuerRfc2136) {
	*out = *in
	out.TsigSecretSecretRef = in.TsigSecretSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerRfc2136.
func (in *ClusterIssuerRfc2136) DeepCopy() *ClusterIssuerRfc2136 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerRfc2136)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerRoute53) DeepCopyInto(out *ClusterIssuerRoute53) {
	*out = *in
	out.AccessKeyIDSecretRef = in.AccessKeyIDSecretRef
	in.Auth.DeepCopyInto(&out.Auth)
	out.SecretAccessKeySecretRef = in.SecretAccessKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerRoute53.
func (in *ClusterIssuerRoute53) DeepCopy() *ClusterIssuerRoute53 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerRoute53)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerSeLinuxOptions) DeepCopyInto(out *ClusterIssuerSeLinuxOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerSeLinuxOptions.
func (in *ClusterIssuerSeLinuxOptions) DeepCopy() *ClusterIssuerSeLinuxOptions {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerSeLinuxOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerSeccompProfile) DeepCopyInto(out *ClusterIssuerSeccompProfile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerSeccompProfile.
func (in *ClusterIssuerSeccompProfile) DeepCopy() *ClusterIssuerSeccompProfile {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerSeccompProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerSecurityContext) DeepCopyInto(out *ClusterIssuerSecurityContext) {
	*out = *in
	out.SeLinuxOptions = in.SeLinuxOptions
	out.SeccompProfile = in.SeccompProfile
	if in.SupplementalGroups != nil {
		in, out := &in.SupplementalGroups, &out.SupplementalGroups
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.Sysctls != nil {
		in, out := &in.Sysctls, &out.Sysctls
		*out = make([]ClusterIssuerSysctls, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerSecurityContext.
func (in *ClusterIssuerSecurityContext) DeepCopy() *ClusterIssuerSecurityContext {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerSecurityContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerSelector) DeepCopyInto(out *ClusterIssuerSelector) {
	*out = *in
	if in.DnsNames != nil {
		in, out := &in.DnsNames, &out.DnsNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DnsZones != nil {
		in, out := &in.DnsZones, &out.DnsZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerSelector.
func (in *ClusterIssuerSelector) DeepCopy() *ClusterIssuerSelector {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerSelfSigned) DeepCopyInto(out *ClusterIssuerSelfSigned) {
	*out = *in
	if in.CrlDistributionPoints != nil {
		in, out := &in.CrlDistributionPoints, &out.CrlDistributionPoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerSelfSigned.
func (in *ClusterIssuerSelfSigned) DeepCopy() *ClusterIssuerSelfSigned {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerSelfSigned)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerServiceAccountRef) DeepCopyInto(out *ClusterIssuerServiceAccountRef) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerServiceAccountRef.
func (in *ClusterIssuerServiceAccountRef) DeepCopy() *ClusterIssuerServiceAccountRef {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerServiceAccountRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerServiceAccountRef1) DeepCopyInto(out *ClusterIssuerServiceAccountRef1) {
	*out = *in
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerServiceAccountRef1.
func (in *ClusterIssuerServiceAccountRef1) DeepCopy() *ClusterIssuerServiceAccountRef1 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerServiceAccountRef1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerSolvers) DeepCopyInto(out *ClusterIssuerSolvers) {
	*out = *in
	in.Dns01.DeepCopyInto(&out.Dns01)
	in.Http01.DeepCopyInto(&out.Http01)
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerSolvers.
func (in *ClusterIssuerSolvers) DeepCopy() *ClusterIssuerSolvers {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerSolvers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerSpec) DeepCopyInto(out *ClusterIssuerSpec) {
	*out = *in
	in.Acme.DeepCopyInto(&out.Acme)
	in.Ca.DeepCopyInto(&out.Ca)
	in.SelfSigned.DeepCopyInto(&out.SelfSigned)
	in.Vault.DeepCopyInto(&out.Vault)
	in.Venafi.DeepCopyInto(&out.Venafi)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerSpec.
func (in *ClusterIssuerSpec) DeepCopy() *ClusterIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerSpec1) DeepCopyInto(out *ClusterIssuerSpec1) {
	*out = *in
	in.Affinity.DeepCopyInto(&out.Affinity)
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]ClusterIssuerImagePullSecrets, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.SecurityContext.DeepCopyInto(&out.SecurityContext)
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]ClusterIssuerTolerations, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerSpec1.
func (in *ClusterIssuerSpec1) DeepCopy() *ClusterIssuerSpec1 {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerSpec1)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerStatus) DeepCopyInto(out *ClusterIssuerStatus) {
	*out = *in
	out.Acme = in.Acme
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ClusterIssuerConditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerStatus.
func (in *ClusterIssuerStatus) DeepCopy() *ClusterIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerSysctls) DeepCopyInto(out *ClusterIssuerSysctls) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerSysctls.
func (in *ClusterIssuerSysctls) DeepCopy() *ClusterIssuerSysctls {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerSysctls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerTolerations) DeepCopyInto(out *ClusterIssuerTolerations) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerTolerations.
func (in *ClusterIssuerTolerations) DeepCopy() *ClusterIssuerTolerations {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerTolerations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerTpp) DeepCopyInto(out *ClusterIssuerTpp) {
	*out = *in
	if in.CaBundle != nil {
		in, out := &in.CaBundle, &out.CaBundle
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	out.CaBundleSecretRef = in.CaBundleSecretRef
	out.CredentialsRef = in.CredentialsRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerTpp.
func (in *ClusterIssuerTpp) DeepCopy() *ClusterIssuerTpp {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerTpp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerVault) DeepCopyInto(out *ClusterIssuerVault) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
	if in.CaBundle != nil {
		in, out := &in.CaBundle, &out.CaBundle
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	out.CaBundleSecretRef = in.CaBundleSecretRef
	out.ClientCertSecretRef = in.ClientCertSecretRef
	out.ClientKeySecretRef = in.ClientKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerVault.
func (in *ClusterIssuerVault) DeepCopy() *ClusterIssuerVault {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerVault)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerVenafi) DeepCopyInto(out *ClusterIssuerVenafi) {
	*out = *in
	out.Cloud = in.Cloud
	in.Tpp.DeepCopyInto(&out.Tpp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerVenafi.
func (in *ClusterIssuerVenafi) DeepCopy() *ClusterIssuerVenafi {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerVenafi)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterIssuerWebhook) DeepCopyInto(out *ClusterIssuerWebhook) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterIssuerWebhook.
func (in *ClusterIssuerWebhook) DeepCopy() *ClusterIssuerWebhook {
	if in == nil {
		return nil
	}
	out := new(ClusterIssuerWebhook)
	in.DeepCopyInto(out)
	return out
}
