//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by {{ .AppName }}. DO NOT EDIT.

package {{ .Version }}

import (
{{- range .Imports }}
	{{ . }}
{{- end }}
)

// +kubebuilder:object:generate=true

// +kubebuilder:object:root=true

// {{ .List }} is a list of {{ .Plural }}.
type {{ .List }} struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []{{ .Kind }} `json:"items"`
}

// +kubebuilder:object:root=true

{{ if .Root.Description }}// {{ .Root.Description  }}{{ end }}
type {{ .Kind }} struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	{{- range .Root.Fields }}
	{{- if .Description }}
	// {{ .Description }}
	{{- end }}
	{{ .Name }} {{ .Type }} `json:"{{ .JSONTag }},omitempty"`
	{{- end }}
}

{{ range $_, $struct := .Structs }}
{{- if ne $struct.Path "status.conditions" }}
{{ if $struct.Description }}// {{ $struct.Description  }}{{ end }}
type {{ $struct.Name }} struct {
	{{- range $_, $field :=  $struct.Fields }}
	{{- if $field.Description }}
	// {{ $field.Description }}
	{{- end }}
	{{- if eq $field.Name "Conditions" }}
    // +deepequal-gen=false
	Conditions []metav1.Condition `json:"conditions,omitempty"`
    {{- else }}
	{{ $field.Name }} {{ $field.Type }} `json:"{{ $field.JSONTag }},omitempty"`
	{{- end }}
    {{- end }}
}
{{- end }}
{{ end }}

{{- range $_, $struct := .Structs }}
{{- range $_, $field :=  $struct.Fields }}
{{- if $field.Enums }}
// {{ $field.EnumName }} represents an enumeration for {{ $field.Name }}
type {{ $field.EnumName }} {{ $field.EnumType }}

var (
{{- range $field.Enums }}
	// {{ .Name }} {{ $field.Name }} enum value {{ .Value }}
	{{ .Name }} {{ $field.EnumName }} = {{ .Value }}
{{- end }}
)
{{ end }}
{{- end }}
{{- end }}