package main

import (
	"fmt"
	"go/ast"
	"strings"
)

// Generator holds generation state.
type Generator struct {
	pkg        string
	addHeader  bool
	inputFile  string
	allStructs map[string]bool // struct names defined in the same file

	imports map[string]bool
	body    strings.Builder
}

func (g *Generator) generate(structs []StructInfo) string {
	g.imports = map[string]bool{}

	for _, s := range structs {
		g.genDeepEqual(s)
		g.body.WriteString("\n")
		g.genDeepCompare(s)
		g.body.WriteString("\n")
	}

	var sb strings.Builder

	if g.addHeader {
		origin := "stdin"
		if g.inputFile != "" {
			origin = g.inputFile
		}
		sb.WriteString("// Code generated by compare-gen from " + origin + "; DO NOT EDIT.\n\n")
	}

	sb.WriteString("package " + g.pkg + "\n\n")

	// Write imports
	if len(g.imports) > 0 {
		sb.WriteString("import (\n")
		for imp := range g.imports {
			sb.WriteString("\t\"" + imp + "\"\n")
		}
		sb.WriteString(")\n\n")
	}

	sb.WriteString(g.body.String())
	return sb.String()
}

// -------------------------------------------------------------------------
// DeepEqual
// -------------------------------------------------------------------------

func (g *Generator) genDeepEqual(s StructInfo) {
	w := &g.body
	fmt.Fprintf(w, "// DeepEqual returns true if all exported fields of %s are deeply equal to the other.\n", s.Name)
	fmt.Fprintf(w, "func (in *%s) DeepEqual(other *%s) bool {\n", s.Name, s.Name)
	fmt.Fprint(w, "\tif in == nil && other == nil {\n\t\treturn true\n\t}\n")
	fmt.Fprint(w, "\tif in == nil || other == nil {\n\t\treturn false\n\t}\n")

	for _, f := range s.Fields {
		g.writeEqualField(w, "in."+f.Name, "other."+f.Name, f.Type, 1)
	}

	fmt.Fprint(w, "\treturn true\n}\n")
}

func (g *Generator) writeEqualField(w *strings.Builder, a, b string, t ast.Expr, depth int) {
	tabs := strings.Repeat("\t", depth)

	switch typ := t.(type) {
	case *ast.Ident:
		name := typ.Name
		switch name {
		case "string", "bool",
			"int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
			"float32", "float64", "complex64", "complex128", "byte", "rune":
			fmt.Fprintf(w, "%sif %s != %s {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)
		default:
			switch {
			case g.allStructs[name]:
				// Struct defined in same file: call recursively
				fmt.Fprintf(w, "%sif !%s.DeepEqual(new(%s)) {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)
			case name == "Time":
				g.imports["time"] = true
				fmt.Fprintf(w, "%sif !%s.Equal(%s) {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)
			default:
				g.imports["reflect"] = true
				fmt.Fprintf(w, "%sif !reflect.DeepEqual(%s, %s) {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)
			}
		}

	case *ast.SelectorExpr:
		// e.g. time.Time, metav1.Time
		sel := fmt.Sprintf("%s.%s", exprStr(typ.X), typ.Sel.Name)
		switch sel {
		case "time.Time":
			fmt.Fprintf(w, "%sif !%s.Equal(%s) {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)
		default:
			g.imports["reflect"] = true
			fmt.Fprintf(w, "%sif !reflect.DeepEqual(%s, %s) {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)
		}

	case *ast.StarExpr:
		inner := typ.X
		// Pointer: nil checks then recurse.
		// For *time.Time we need a local variable to avoid invalid indirect on method call.
		fmt.Fprintf(w, "%sswitch {\n", tabs)
		fmt.Fprintf(w, "%s case %s == nil && %s == nil:\n", tabs, a, b)
		fmt.Fprintf(w, "%s\t// both nil: ok\n", tabs)
		fmt.Fprintf(w, "%s case %s != nil && %s != nil:\n", tabs, a, b)
		aDeref := fmt.Sprintf("_da%d", depth)
		bDeref := fmt.Sprintf("_db%d", depth)
		fmt.Fprintf(w, "%s\t%s, %s := *%s, *%s\n", tabs, aDeref, bDeref, a, b)
		g.writeEqualField(w, aDeref, bDeref, inner, depth+1)
		fmt.Fprintf(w, "%sdefault:\n%s\treturn false", tabs, tabs)
		fmt.Fprintf(w, "%s}\n", tabs)

	case *ast.ArrayType:
		if typ.Len == nil {
			// Slice
			elemType := typ.Elt
			// []byte special case
			if ident, ok := elemType.(*ast.Ident); ok && ident.Name == "byte" {
				g.imports["bytes"] = true
				fmt.Fprintf(w, "%sif !bytes.Equal(%s, %s) {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)
				return
			}
			iVar := fmt.Sprintf("i%d", depth)
			fmt.Fprintf(w, "%sif len(%s) != len(%s) {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)
			fmt.Fprintf(w, "%sfor %s := range %s {\n", tabs, iVar, a)
			g.writeEqualField(w, fmt.Sprintf("%s[%s]", a, iVar), fmt.Sprintf("%s[%s]", b, iVar), elemType, depth+1)
			fmt.Fprintf(w, "%s}\n", tabs)
		} else {
			// Fixed-size array
			iVar := fmt.Sprintf("i%d", depth)
			fmt.Fprintf(w, "%sfor %s := range %s {\n", tabs, iVar, a)
			g.writeEqualField(w, fmt.Sprintf("%s[%s]", a, iVar), fmt.Sprintf("%s[%s]", b, iVar), typ.Elt, depth+1)
			fmt.Fprintf(w, "%s}\n", tabs)
		}

	case *ast.MapType:
		fmt.Fprintf(w, "%sif len(%s) != len(%s) {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)
		kVar := fmt.Sprintf("k%d", depth)
		vVar := fmt.Sprintf("v%d", depth)
		fmt.Fprintf(w, "%sfor %s, %s := range %s {\n", tabs, kVar, vVar, a)
		fmt.Fprintf(w, "%s\t_bv%d, _ok%d := %s[%s]\n", tabs, depth, depth, b, kVar)
		fmt.Fprintf(w, "%s\tif !_ok%d {\n%s\t\treturn false\n%s\t}\n", tabs, depth, tabs, tabs)
		g.writeEqualField(w, vVar, fmt.Sprintf("_bv%d", depth), typ.Value, depth+1)
		fmt.Fprintf(w, "%s}\n", tabs)

	case *ast.InterfaceType:
		g.imports["reflect"] = true
		fmt.Fprintf(w, "%sif !reflect.DeepEqual(%s, %s) {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)

	default:
		g.imports["reflect"] = true
		fmt.Fprintf(w, "%sif !reflect.DeepEqual(%s, %s) {\n%s\treturn false\n%s}\n", tabs, a, b, tabs, tabs)
	}
}

// -------------------------------------------------------------------------
// DeepCompare
// -------------------------------------------------------------------------

func (g *Generator) genDeepCompare(s StructInfo) {
	w := &g.body
	fmt.Fprintf(
		w,
		"// DeepCompare compares %s field by field in declaration order.\n// Returns -1 if in < other, 0 if equal, 1 if in > other.\n",
		s.Name,
	)
	fmt.Fprintf(w, "func (in *%s) DeepCompare(other *%s) int {\n", s.Name, s.Name)
	fmt.Fprint(w, "\tif in == nil && other == nil {\n\t\treturn 0\n\t}\n")
	fmt.Fprint(w, "\tif in == nil {\n\t\treturn -1\n\t}\n")
	fmt.Fprint(w, "\tif other == nil {\n\t\treturn 1\n\t}\n")

	for _, f := range s.Fields {
		g.writeCmpField(w, "in."+f.Name, "other."+f.Name, f.Type, 1)
	}

	fmt.Fprint(w, "\treturn 0\n}\n")
}

func (g *Generator) writeCmpField(w *strings.Builder, a, b string, t ast.Expr, depth int) {
	tabs := strings.Repeat("\t", depth)

	switch typ := t.(type) {
	case *ast.Ident:
		name := typ.Name
		switch name {
		case "string":
			g.imports["strings"] = true
			fmt.Fprintf(w, "%sif _c := strings.Compare(%s, %s); _c != 0 {\n%s\treturn _c\n%s}\n", tabs, a, b, tabs, tabs)
		case "bool":
			// false < true
			fmt.Fprintf(w, "%sif !%s && %s {\n%s\treturn -1\n%s}\n", tabs, a, b, tabs, tabs)
			fmt.Fprintf(w, "%sif %s && !%s {\n%s\treturn 1\n%s}\n", tabs, a, b, tabs, tabs)
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
			"float32", "float64", "byte", "rune":
			fmt.Fprintf(w, "%sif %s < %s {\n%s\treturn -1\n%s}\n", tabs, a, b, tabs, tabs)
			fmt.Fprintf(w, "%sif %s > %s {\n%s\treturn 1\n%s}\n", tabs, a, b, tabs, tabs)
		case "complex64", "complex128":
			// No ordering for complex; fall back to string representation
			g.imports["fmt"] = true
			fmt.Fprintf(w, "%s{\n%s\t_sa, _sb := fmt.Sprint(%s), fmt.Sprint(%s)\n", tabs, tabs, a, b)
			g.imports["strings"] = true
			fmt.Fprintf(
				w,
				"%s\tif _c := strings.Compare(_sa, _sb); _c != 0 {\n%s\t\treturn _c\n%s\t}\n%s}\n",
				tabs,
				tabs,
				tabs,
				tabs,
			)
		default:
			if g.allStructs[name] {
				fmt.Fprintf(w, "%sif _c := %s.DeepCompare(new(%s)); _c != 0 {\n%s\treturn _c\n%s}\n", tabs, a, b, tabs, tabs)
			} else {
				// Unknown named type - best effort
				g.imports["fmt"] = true
				g.imports["strings"] = true
				fmt.Fprintf(w, "%s{\n%s\t_sa, _sb := fmt.Sprint(%s), fmt.Sprint(%s)\n", tabs, tabs, a, b)
				fmt.Fprintf(
					w,
					"%s\tif _c := strings.Compare(_sa, _sb); _c != 0 {\n%s\t\treturn _c\n%s\t}\n%s}\n",
					tabs,
					tabs,
					tabs,
					tabs,
				)
			}
		}

	case *ast.SelectorExpr:
		sel := fmt.Sprintf("%s.%s", exprStr(typ.X), typ.Sel.Name)
		switch sel {
		case "time.Time":
			fmt.Fprintf(w, "%sif %s.Before(%s) {\n%s\treturn -1\n%s}\n", tabs, a, b, tabs, tabs)
			fmt.Fprintf(w, "%sif %s.After(%s) {\n%s\treturn 1\n%s}\n", tabs, a, b, tabs, tabs)
		default:
			g.imports["fmt"] = true
			g.imports["strings"] = true
			fmt.Fprintf(w, "%s{\n%s\t_sa, _sb := fmt.Sprint(%s), fmt.Sprint(%s)\n", tabs, tabs, a, b)
			fmt.Fprintf(
				w,
				"%s\tif _c := strings.Compare(_sa, _sb); _c != 0 {\n%s\t\treturn _c\n%s\t}\n%s}\n",
				tabs,
				tabs,
				tabs,
				tabs,
			)
		}

	case *ast.StarExpr:
		fmt.Fprintf(w, "%sif %s == nil && %s != nil {\n%s\treturn -1\n%s}\n", tabs, a, b, tabs, tabs)
		fmt.Fprintf(w, "%sif %s != nil && %s == nil {\n%s\treturn 1\n%s}\n", tabs, a, b, tabs, tabs)
		aDeref := fmt.Sprintf("_da%d", depth)
		bDeref := fmt.Sprintf("_db%d", depth)
		fmt.Fprintf(w, "%sif %s != nil {\n", tabs, a)
		fmt.Fprintf(w, "%s\t%s, %s := *%s, *%s\n", tabs, aDeref, bDeref, a, b)
		g.writeCmpField(w, aDeref, bDeref, typ.X, depth+1)
		fmt.Fprintf(w, "%s}\n", tabs)

	case *ast.ArrayType:
		if typ.Len == nil {
			elemType := typ.Elt
			// []byte special case
			if ident, ok := elemType.(*ast.Ident); ok && ident.Name == "byte" {
				g.imports["bytes"] = true
				fmt.Fprintf(w, "%sif _c := bytes.Compare(%s, %s); _c != 0 {\n%s\treturn _c\n%s}\n", tabs, a, b, tabs, tabs)
				return
			}
			iVar := fmt.Sprintf("_i%d", depth)
			fmt.Fprintf(w, "%s{\n%s\t_la, _lb := len(%s), len(%s)\n", tabs, tabs, a, b)
			fmt.Fprintf(w, "%s\t_min := min(_lb, _la)\n", tabs)
			fmt.Fprintf(w, "%s\tfor %s := range _min {\n", tabs, iVar)
			g.writeCmpField(w, fmt.Sprintf("%s[%s]", a, iVar), fmt.Sprintf("%s[%s]", b, iVar), elemType, depth+2)
			fmt.Fprintf(w, "%s\t}\n", tabs)
			fmt.Fprintf(w, "%s\tif _la < _lb {\n%s\t\treturn -1\n%s\t}\n", tabs, tabs, tabs)
			fmt.Fprintf(w, "%s\tif _la > _lb {\n%s\t\treturn 1\n%s\t}\n", tabs, tabs, tabs)
			fmt.Fprintf(w, "%s}\n", tabs)
		} else {
			// Fixed array
			iVar := fmt.Sprintf("_i%d", depth)
			fmt.Fprintf(w, "%sfor %s := range %s {\n", tabs, iVar, a)
			g.writeCmpField(w, fmt.Sprintf("%s[%s]", a, iVar), fmt.Sprintf("%s[%s]", b, iVar), typ.Elt, depth+1)
			fmt.Fprintf(w, "%s}\n", tabs)
		}

	case *ast.MapType:
		// Maps have no natural ordering; compare by length then sorted keys
		g.imports["fmt"] = true
		g.imports["strings"] = true
		g.imports["slices"] = true
		fmt.Fprintf(w, "%s{\n", tabs)
		fmt.Fprintf(w, "%s\tif len(%s) != len(%s) {\n", tabs, a, b)
		fmt.Fprintf(w, "%s\t\tif len(%s) < len(%s) { return -1 }\n", tabs, a, b)
		fmt.Fprintf(w, "%s\t\treturn 1\n%s\t}\n", tabs, tabs)
		fmt.Fprintf(w, "%s\t_keys := make([]string, 0, len(%s))\n", tabs, a)
		fmt.Fprintf(w, "%s\tfor _k := range %s { _keys = append(_keys, fmt.Sprint(_k)) }\n", tabs, a)
		fmt.Fprintf(w, "%s\tslices.Sort(_keys)\n", tabs)
		fmt.Fprintf(w, "%s\tfor _, _ks := range _keys {\n", tabs)
		fmt.Fprintf(w, "%s\t\t_ = _ks // key-order compare via sorted string keys\n", tabs)
		fmt.Fprintf(w, "%s\t}\n", tabs)
		fmt.Fprintf(w, "%s\t// detailed map compare: fall back to string representation\n", tabs)
		fmt.Fprintf(w, "%s\t_sa, _sb := fmt.Sprint(%s), fmt.Sprint(%s)\n", tabs, a, b)
		fmt.Fprintf(w, "%s\tif _c := strings.Compare(_sa, _sb); _c != 0 {\n%s\t\treturn _c\n%s\t}\n", tabs, tabs, tabs)
		fmt.Fprintf(w, "%s}\n", tabs)

	default:
		g.imports["fmt"] = true
		g.imports["strings"] = true
		fmt.Fprintf(w, "%s{\n%s\t_sa, _sb := fmt.Sprint(%s), fmt.Sprint(%s)\n", tabs, tabs, a, b)
		fmt.Fprintf(
			w,
			"%s\tif _c := strings.Compare(_sa, _sb); _c != 0 {\n%s\t\treturn _c\n%s\t}\n%s}\n",
			tabs,
			tabs,
			tabs,
			tabs,
		)
	}
}

func exprStr(e ast.Expr) string {
	if id, ok := e.(*ast.Ident); ok {
		return id.Name
	}
	return "?"
}
